Catch errors in unicorn
3Hren/cocaine-plugins pull request #102
Opened 2017-01-18 14:16 UTC by antmat

Catch exceptions in unicorn calls and process calbacks in executor to prevent deadlocks.

2017-01-18 14:21 UTC, 3Hren requested changes

2017-01-18 14:21 UTC, 3Hren commented on unicorn/src/unicorn/zookeeper.cpp
> +    } catch (...) {
Looks like boilerplate, isn't it?

2017-01-18 14:24 UTC, antmat commented on unicorn/src/unicorn/zookeeper.cpp
> +    } catch (...) {
suggestions?

2017-01-18 14:26 UTC, 3Hren commented on unicorn/src/unicorn/zookeeper.cpp
> +    } catch (...) {
goto

2017-01-18 14:27 UTC, antmat commented on unicorn/src/unicorn/zookeeper.cpp
> +    } catch (...) {
nice catch! I think I can use it

2017-01-18 14:40 UTC, antmat commented on unicorn/src/unicorn/zookeeper.cpp
> +    } catch (...) {
try_run([]{
        zk.put(handler.path, handler.encoded_value, handler.version, handler);
    }, handler.callback, *executor);

Would be better?

2017-01-18 15:02 UTC, antmat commented
@3Hren @karitra PTAL

2017-01-18 16:31 UTC, karitra approved these changes
LGTM

2017-01-18 19:52 UTC, 3Hren requested changes

2017-01-18 19:52 UTC, 3Hren commented on unicorn/src/unicorn/zookeeper.cpp
> +    auto scope = std::make_shared<zk_scope_t>();
What's the purpose of this variable?

2017-01-18 19:52 UTC, 3Hren commented on unicorn/src/unicorn/zookeeper.cpp
> +    auto scope = std::make_shared<zk_scope_t>();
And this?

2017-01-18 19:52 UTC, 3Hren commented on unicorn/src/zookeeper/connection.cpp
> +    std::function<void()> f = [=]{
And this?

2017-01-18 19:55 UTC, 3Hren requested changes

2017-01-18 19:55 UTC, 3Hren commented on unicorn/src/unicorn/zookeeper.cpp
> +
Excess.

2017-01-18 19:55 UTC, 3Hren commented on unicorn/src/unicorn/zookeeper.cpp
> +auto try_run(F runnable, std::function<void(std::future<Result>)>& callback, api::executor_t& executor) -> void {
Make static or put into anonymous namespace (preferred).

2017-01-18 19:55 UTC, 3Hren commented on unicorn/src/unicorn/zookeeper.cpp
> +
Excess.

2017-01-18 19:56 UTC, 3Hren commented
And the biggest trouble: it doesn't compile.

2017-01-19 05:14 UTC, antmat commented on unicorn/src/unicorn/zookeeper.cpp
> +    auto scope = std::make_shared<zk_scope_t>();
it's a scope for zk handlers.

2017-01-19 05:15 UTC, antmat commented on unicorn/src/unicorn/zookeeper.cpp
> +auto try_run(F runnable, std::function<void(std::future<Result>)>& callback, api::executor_t& executor) -> void {
It's already there

2017-01-19 05:22 UTC, antmat commented
considering build - looks like build started before PR in core was merged, because it builds fine on my linux dev server and mac.

2017-01-19 05:24 UTC, antmat commented
and because core can not be built on linux)

2017-01-19 11:53 UTC, merged