Isolation daemon workers metrics
3Hren/cocaine-plugins pull request #123
Opened 2017-03-30 16:17 UTC by karitra

Retrieve workers metrics from _Cocaine isolation daemon_ (aka [stout](https://github.com/noxiouz/stout)), register resulting signals within metrics service hub, show (some, probably after post-processing) in cocaine-tool info. Special attention should be paid to short living workers, their post-mortem metrics should be gathered similarly.

**WIP: experimental, for early review only, don't merge!**

#### TODO:
 - adjust and stabilize metrics list, types
 - stabilize Cocaine <-> Isolation Daemon protocol
 - add tests for designed protocol to isolation mock service
 - make poll calls work in case of Isolation Daemon absence

2017-03-30 19:07 UTC, 3Hren requested changes

2017-03-30 19:07 UTC, 3Hren commented on docker/isolate.hpp
> +    spool(std::shared_ptr<api::spool_handle_base_t> handle);
Leave all renaming stuff for a separate PR.

2017-03-30 19:07 UTC, 3Hren commented on node/include/cocaine/api/isolate.hpp
> +    ~metrics_handle_base_t() {}
`= default`.

2017-03-30 19:07 UTC, 3Hren commented on node/src/isolate/external.cpp
> +          metrics_handle(std::move(handle))
Seems like there is no need to store handle inside this struct.

2017-03-30 19:07 UTC, 3Hren commented on node/src/node/engine.cpp
> +            alive.resize(pool.size());
Reserve? Instead your alive pool is doubled.

2017-03-30 19:16 UTC, 3Hren requested changes

2017-03-30 19:16 UTC, 3Hren commented on node/src/node/engine.cpp
> +// TODO: should that stuff be moved to separate compilation unit?
Yep. Engine is too big enough.

2017-03-30 19:16 UTC, 3Hren commented on node/src/node/engine.cpp
> +    mutable std::mutex prg_lock;
Didn't get the idea about unsynchronized access to the purgatory.

2017-03-31 05:54 UTC, 3Hren requested changes

2017-03-31 05:54 UTC, 3Hren commented on node/include/cocaine/detail/service/node/engine.hpp
> +    class metrics_retriever_t;
There is no need to introduce impl in `detail` files.

2017-04-07 11:28 UTC, karitra commented
Protocol neither tested nor complete, overall implementation is still _moving target_, error responses must be processed, local integration tests with _stout_ are scheduled to be done, overall tests are in wish-list, but updates may land into another PR, so @3Hren, @antmat  PTAL.

2017-04-10 13:53 UTC, 3Hren requested changes

2017-04-10 13:53 UTC, 3Hren commented on docker/isolate.cpp
> +docker_t::metrics(const dynamic_t&, std::shared_ptr<api::metrics_handle_base_t>) const
I'd rather call `on_data({})` instead of ignoring.

2017-04-10 13:53 UTC, 3Hren commented on docker/isolate.hpp
> +    virtual
Either `virtual` or `override`.

2017-04-10 13:53 UTC, 3Hren commented on node/include/cocaine/idl/isolate.hpp
> +            dynamic_t
Comments.

2017-04-10 13:53 UTC, 3Hren commented on node/include/cocaine/idl/isolate.hpp
> +            dynamic_t
Comments.

2017-04-10 13:53 UTC, 3Hren commented on node/include/cocaine/idl/isolate.hpp
> +
Return back.

2017-04-10 13:53 UTC, 3Hren commented on node/src/isolate/external.cpp
> +    auto _inner = inner;
It's already captured by `load`, isn't it?

2017-04-10 13:53 UTC, 3Hren commented on node/src/isolate/process.cpp
> +    COCAINE_LOG_WARNING(m_log, "legacy_process::metrics not implemented");
Call handle instead.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/engine.cpp
> +    if (loop) {
Why?

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/engine.cpp
> +        if (isolate) {
We get either valid pointer or exception. This is unnecessary check.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/engine.cpp
> +    observers->emplace_back(observer);
You have `attach_pool_observer`, use it!

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/engine.cpp
> +    auto was_despawned = false;
Return from lambda instead.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/engine.cpp
> +            boost::for_each(observers, [&](const std::shared_ptr<pool_observer>& o) {
There is no profit for `boost::for_each` comparing with range-based for.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/engine.cpp
> +            boost::for_each(observers, [](const std::shared_ptr<pool_observer>& o) {
The same here.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/engine.cpp
> +        boost::for_each(observers, [&](const std::shared_ptr<pool_observer>& o) {
The same.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +        { "cpu", false},
Use enums instead of bool. It improves readability. Thus, there will be no need for separate comment.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +namespace aux {
We use `detail` or anonymous namespace for details.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +    boost::for_each(worker_metrics.common_counters, [&](const counters_record_type &worker_record) {
Use range-based for.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +worker_metrics_t::operator=(metrics_aggregate_proxy_t&& proxy) -> worker_metrics_t& {
Unobvious assignment operator usage with non-equal `this` and `other` types. Use method instead.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +                if (uuid.compare("error") == 0) {
Just ==.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +                    // If isolate daemon sends us uuid we don't know about,
Then this is very strange. Ideally we should track uuids for slaves that were spawned somewhere here, and warn if the isolate daemon doesn't sent metrics for it for a long time.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +                    tie(stat_it, std::ignore) = stats_table.emplace(uuid, worker_metrics_t{ctx, app_name, uuid});
std::tie?

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +        return ! errors.empty();
Space.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +    errors_ref() -> const std::vector<error_t>& {
Just `errors`, rename field if necessary.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +    bool processed;
Why do we need such field?

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +            const auto pos = name.find('.');
I feel that mangled-naming-processing stuff unnatural here. Decompose it from.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +            // note: e is boost::bad_get in current implementaion
Then catch it.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +   uuid_requested{ctx.metrics_hub().counter<std::uint64_t>(cocaine::format("{}.uuid_requested", name))},
Replace with `make_counter(ctx, name)` or something to reduce boilerplate.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +            const auto& errors = processor.errors_ref();
Something wrong with indents here.

2017-04-10 13:53 UTC, 3Hren commented on node/src/node/isometrics.hpp
> +        despawned() -> void override {}
I think we should drop `spawned`/`despawned` overloads without an `uuid` parameter.

2017-04-10 13:53 UTC, 3Hren commented on node/tests/isolate_mock.cpp
> +        if (getrusage(RUSAGE_THREAD, &ru)) {
```
        #if defined(__linux__)
            getrusage(RUSAGE_THREAD, &ru);
        #else
            getrusage(RUSAGE_SELF, &ru);
        #endif
```

2017-04-10 16:40 UTC, karitra commented on node/src/node/isometrics.cpp
> +                    // If isolate daemon sends us uuid we don't know about,
Well `update stamp` checking will be implemented either on this or on next iteration, stay tuned.

2017-04-11 05:55 UTC, 3Hren approved these changes

2017-04-11 10:41 UTC, karitra commented on node/src/node/isometrics.cpp
> +                    // If isolate daemon sends us uuid we don't know about,
_update stamp checking_ -  done in ebb6e99

Ready to merge in order not to block engine_t (and node service in general) development, @3Hren, @antmat  PTAL. 

Stalled **TODO items** will be implemented within separate PR on _stout_ willingness.

2017-04-11 10:42 UTC, 3Hren commented on node/src/node/isometrics.cpp
> +                    // If isolate daemon sends us uuid we don't know about,
Ok, waiting for @antmat review.

2017-04-11 11:46 UTC, antmat reviewed
Still need to read and understand the main part - isometrics.[ch]pp

2017-04-11 11:46 UTC, antmat commented on node/src/isolate/external.cpp
> +    stream.apply([&](decltype(stream.unsafe())& stream){
why do you need synchronized here?

2017-04-11 11:46 UTC, antmat commented on node/src/isolate/external.cpp
> +            _inner->session->detach(e.code());
Maybe it not really required here

2017-04-11 11:46 UTC, antmat commented on node/src/isolate/external.cpp
> +    auto load = std::make_shared<metrics_load_t>(inner, query, handle);
Why do you need load here? Looks like there is no queue for metrics requests

2017-04-11 11:46 UTC, antmat commented on node/src/isolate/external.cpp
> +        } else {
in else block handle will never be called

2017-04-11 11:46 UTC, antmat commented on node/src/node/engine.cpp
> +engine_t::attach_pool_observer(const std::shared_ptr<pool_observer>& observer) {
not an issue, but why not pass by value and move?

2017-04-11 11:46 UTC, antmat commented on node/src/node/isometrics.cpp
> +    dump_uuids(std::ostream& os, const std::string& logo, const Container& arr) -> void {
Looks like it's some kind of debug helpers. We already have newly introduced display helpers in core, you can use them, besides you can use logger to unify your debug output. If you don't want to use context_t provided logger you can do smth like https://github.com/3Hren/cocaine-plugins/blob/v0.12.13/vicodyn/include/cocaine/vicodyn/debug.hpp
@3Hren Can we think about adding such development debug functionality to core?

2017-04-11 11:46 UTC, antmat commented on node/tests/isolate_mock.cpp
> +        operator()(const std::map<std::string, std::string>& data) -> std::string {
Again - you can use display_traits for this

2017-04-11 11:46 UTC, antmat commented on node/tests/isolate_mock.cpp
> +    boost::optional<std::shared_ptr<dispatch_type>>
result_type

2017-04-11 11:46 UTC, antmat commented on node/tests/isolate_mock.cpp
> +    boost::optional<std::shared_ptr<dispatch_type>>
result_type

2017-04-11 11:46 UTC, antmat commented on node/tests/isolate_mock.cpp
> +struct metrics_slot_t:
In general it's now optional to create a separate slot - you can use a function receiving headers, tuple_type, upstream_type, but it's up to you.

2017-04-11 12:10 UTC, karitra commented on node/src/isolate/external.cpp
> +    stream.apply([&](decltype(stream.unsafe())& stream){
It is taken by analogy from code of spool/spawn, mostly copy-pasted brainlessly, partly for code-base consistency. It seems that it'll not do any harm.

2017-04-11 12:10 UTC, karitra commented on node/src/isolate/external.cpp
> +            _inner->session->detach(e.code());
for code-base consistency.

2017-04-11 12:19 UTC, antmat commented on node/src/isolate/external.cpp
> +    stream.apply([&](decltype(stream.unsafe())& stream){
I don't think that aquiring a mutex for code consistency is a good idea) other handles can be cancelled from other thread, and it looks like this one can not.

2017-04-11 12:27 UTC, karitra commented on node/src/node/isometrics.cpp
> +    dump_uuids(std::ostream& os, const std::string& logo, const Container& arr) -> void {
Will consider it on next developing iteration.

2017-04-11 12:31 UTC, karitra commented on node/src/isolate/external.cpp
> +    auto load = std::make_shared<metrics_load_t>(inner, query, handle);
For code-base consistency with spool/spawn, initial release has metrics load queue, but it was removed as redundant for polling task, as it seems not crucial to loose some payload for it.

2017-04-11 12:55 UTC, antmat approved these changes
Looks ok, I'll try to take a deeper look later

2017-04-11 12:55 UTC, antmat commented on node/src/node/isometrics.hpp
> +    constexpr auto METRICS_POLL_INTERVAL_S = 2u;
looks like we define constants in a similar to varible way - lower case with underscores

2017-04-11 12:55 UTC, antmat commented on node/src/node/isometrics.hpp
> +enum class CounterType : unsigned {
style

2017-04-11 12:55 UTC, antmat commented on node/src/node/isometrics.hpp
> +    if (!node_config) {
is this a good idea to return nullptr? Besides for some(very strange) reasons node service can have a different name (not 'node').

2017-04-11 12:55 UTC, antmat commented on node/src/node/isometrics.cpp
> +    constexpr auto PURGATORY_QUEUE_BOUND = 8 * 1024;
seems that lowercase is better in this case

2017-04-12 13:18 UTC, merged