Unified Cocaine ACL Tooling
3Hren/cocaine-plugins pull request #140
Opened 2017-06-16 16:29 UTC by karitra

## Unified Cocaine ACL Tooling (UNICAT) plugin

Service for unified ACL records altering.

**Deeply WIP, don't merge, by no means, yet review abusive**

**TODO:**
- [ ] complete grant/revoke pair for storage, unicorn
- [ ] ensure correct Unicorn prefix access semantics
- [ ] find better place for common stuff: `metainfo_t`, `indentity_t`, `flags_t`
- [ ] robust config processing (compile list of storages, unicorns, etc)
- [x] ~~tooling integration (separate PR in tools)~~
- [ ] ensure correct cid/uid access restriction for grant/revoke
- [ ] additional methods: view/reset 
- [ ] tests

2017-06-29 11:55 UTC, karitra commented
Yet lacks functional tests and marginal cases testing, but @antmat & @3Hren PTAL.

2017-06-30 15:40 UTC, karitra commented
Yet lacks functional tests and marginal cases testing, but @antmat & @3Hren PTAL.

**UPD2**: following issue hopefully solved in 9b5c911.
**UPD1**: oops, testing results for unicorn, please standby:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::t
hread_resource_error> >'
  what():  boost thread: trying joining itself: Resource deadlock avoided
```

2017-07-07 13:52 UTC, karitra commented
@antmat, @3Hren, pls, don't beat me up for such a huge pile of garbage, but it seems the only way to animate all those async stuff, hopefully it will be party refactored out, so PTAL.

2017-07-10 11:42 UTC, 3Hren commented
At last:

```
Undefined symbols for architecture x86_64:
  "_msgpack_unpack", referenced from:
      void cocaine::api::storage_t::get<cocaine::auth::metainfo_t>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::future<cocaine::auth::metainfo_t>)>)::'lambda'(std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >)::operator()(std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >) const in storage.cpp.o
  "_msgpack_zone_destroy", referenced from:
      void cocaine::api::storage_t::get<cocaine::auth::metainfo_t>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::future<cocaine::auth::metainfo_t>)>)::'lambda'(std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >)::operator()(std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >) const in storage.cpp.o
  "_msgpack_zone_init", referenced from:
      void cocaine::api::storage_t::get<cocaine::auth::metainfo_t>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::future<cocaine::auth::metainfo_t>)>)::'lambda'(std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >)::operator()(std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >) const in storage.cpp.o
```

2017-07-10 11:42 UTC, 3Hren requested changes

2017-07-10 11:42 UTC, 3Hren commented on unicat/include/cocaine/auth/metainfo.hpp
> +            throw std::bad_cast();
It's really misleading exception type. Consider `std::invalid_argument` instead.

2017-07-10 11:42 UTC, 3Hren commented on unicat/include/cocaine/detail/forwards.hpp
> +#pragma once
Avoid `detail` section, especially in plugins, move in `src` instead.

2017-07-10 11:42 UTC, 3Hren commented on unicat/src/backend/backend.hpp
> +        scope = s;
What to do with previous scope?

2017-07-10 11:42 UTC, 3Hren commented on unicat/src/backend/unicorn.cpp
> +    dbg("unicorn backend is alive");
Do we need these logs?

2017-07-10 11:42 UTC, 3Hren commented on unicat/src/backend/unicorn.cpp
> +    dbg("unicorn backend is dead");
And this.

2017-07-10 11:42 UTC, 3Hren commented on unicat/src/completion.hpp
> +                        continue;
else?

2017-07-10 11:42 UTC, 3Hren commented on unicat/src/metainfo.cpp
> +#if 0
Drop this doubtful stuff.

2017-07-10 11:42 UTC, 3Hren commented on unicat/src/module.cpp
> +        return cocaine::api::preconditions_t{COCAINE_MAKE_VERSION(0, 12, 0)};
12.14

2017-07-10 11:42 UTC, 3Hren commented on unicat/src/unicat.cpp
> +            separated[cu::scheme_from_string(scheme)]
Simplify.

2017-07-10 13:38 UTC, karitra commented
@3Hren PTAL.

2017-07-10 14:43 UTC, 3Hren commented on unicat/src/unicat.cpp
> +    log_requested_entities(std::shared_ptr<logging::logger_t> log, const std::vector<cu::entity_type>& entities)
Seems like dead code.

2017-07-10 14:53 UTC, karitra commented on unicat/src/unicat.cpp
> +    log_requested_entities(std::shared_ptr<logging::logger_t> log, const std::vector<cu::entity_type>& entities)
Yep, but it'll come handy in case of debug, should it be removed?

2017-07-11 11:47 UTC, karitra commented
@3Hren, PTAL.

2017-07-11 13:11 UTC, 3Hren approved these changes

2017-07-12 09:55 UTC, karitra commented
Need bit more testing, probably unit-tests for metainfo alter cases + test for unicorn path, more intensive load test, exceptional cases test, but ready to be merged in order to be able to move further.

2017-07-13 11:10 UTC, merged