Vicodyn
3Hren/cocaine-plugins pull request #86
Opened 2016-12-13 10:19 UTC by antmat

userspace router and gateway.
Please note: there  are some commits related to locator chages. I'll detach them as far as this PR is closed https://github.com/3Hren/cocaine-plugins/pull/84

2016-12-13 11:34 UTC, antmat commented
@3Hren PTAL

2016-12-20 13:20 UTC, 3Hren requested changes

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/include/cocaine/api/peer/pool.hpp
> +    virtual ~pool_t() {}
`=default`

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/include/cocaine/api/peer/pool.hpp
> +    /**
Transform to `///` doc comments.

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/include/cocaine/repository/peer/pool.hpp
> +                -> ptr_type = 0;
Too much whitespaces?

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/src/gateway/vicodyn.cpp
> +        auto actor = context.remove(prefix + proxy_pair.second.proxy.name());
Since we're gateway now, it seems unnecessary to add virtual services to the context.

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/src/gateway/vicodyn.cpp
> +
Blank.

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/src/vicodyn/peer.cpp
> +    logger(context.log("TODO:NAME PEER")),
Do it.

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/src/vicodyn/peer.cpp
> +#include <cocaine/utility/future.hpp>
Here.

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/src/vicodyn/peer/pool/basic.cpp
> +        retry_cnt(args.as_object().at("retry_cnt", 3ul).as_uint()),
retry cunt? count? cent?

2016-12-20 13:20 UTC, 3Hren commented on unicorn/src/cluster/unicorn.cpp
> +                if(uuid == locator.uuid()) {
What Unicorn's doing here?

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/include/cocaine/gateway/vicodyn.hpp
> +    static std::string prefix;
Move to cpp.

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/include/cocaine/gateway/vicodyn.hpp
> +    typedef std::map<std::string, proxy_description_t> proxy_map_t;
Write a description what key means (with example). Here, the key is prefixed or not?

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/src/gateway/vicodyn.cpp
> +    if(name.find(prefix) == 0) {
boost::starts_with

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/include/cocaine/vicodyn/peer/pool/basic.hpp
> +    auto unregister_real(const std::string& uuid) -> void override;
deregister

2016-12-20 13:20 UTC, 3Hren commented on vicodyn/include/cocaine/api/peer/pool.hpp
> +    auto unregister_real(const std::string& uuid) -> void = 0;
deregister

2016-12-20 14:24 UTC, antmat commented on unicorn/src/cluster/unicorn.cpp
> +                if(uuid == locator.uuid()) {
Fixed a bug related to announcing local service as remote. That was important for vicodyn, but got here by mistake

2016-12-21 12:50 UTC, merged