Vicodyn tuning
3Hren/cocaine-plugins pull request #97
Opened 2016-12-29 07:52 UTC by antmat

2016-12-29 09:33 UTC, 3Hren requested changes

2016-12-29 09:33 UTC, 3Hren commented on vicodyn/src/vicodyn/queue/invocation.cpp
> +                    execute(session, *it);
Infinite loop?

2016-12-29 09:33 UTC, 3Hren commented on vicodyn/include/cocaine/api/peer/pool.hpp
> +                io::upstream_ptr_t downstream) -> std::shared_ptr<cocaine::vicodyn::queue::send_t> = 0;
Seems unnecessary.

2016-12-29 14:30 UTC, 3Hren requested changes

2016-12-29 14:30 UTC, 3Hren commented on vicodyn/src/vicodyn/queue/invocation.cpp
> +                    for(auto& op: other.m_operations) {
Error here.

2017-01-10 14:31 UTC, antmat commented on vicodyn/src/vicodyn/queue/invocation.cpp
> +                    execute(session, *it);
Cupertino, CA 95014

2017-01-11 11:16 UTC, merged